settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: article
    path: .
    commands:
      build:
        status: true
        method: go build -o ./bin/article ./svc/article/cmd/server/rest
      run:
        status: true
        method: ./bin/article
    watcher:
      extensions:
        - go
      paths:
        - /

  - name: admin
    path: .
    commands:
      build:
        status: true
        method: go build -o ./bin/admin ./svc/admin/cmd/server/rest
      run:
        status: true
        method: ./bin/admin
    watcher:
      extensions:
        - go
      paths:
        - /
