settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: server
    path: .
    commands:
      build:
        status: true
        method: go build -o ./bin/server ./cmd/server
      run:
        status: true
        method: ./bin/server
    watcher:
      extensions:
        - go
      paths:
        - /
